package runtime.basic.main_exception

import kotlin.test.*

@Test fun runTest() {
    throw Error("Hello!")
}
